package packagecheck

import (
	"path/filepath"
	"testing"

	"github.com/garagon/aguara/internal/intel"
)

func TestParseCargo_RegistryOnly(t *testing.T) {
	target := Target{
		Ecosystem: intel.EcosystemCargo,
		Path:      filepath.Join("testdata", "cargo-compromised", "Cargo.lock"),
		Source:    "Cargo.lock",
	}
	refs, err := ParseCargo(target)
	if err != nil {
		t.Fatalf("ParseCargo: %v", err)
	}
	want := map[string]string{
		"innocent-crate":    "0.1.0",
		"compromised-crate": "1.2.3",
		"with-deps":         "0.5.0",
	}
	if len(refs) != len(want) {
		t.Fatalf("refs = %d, want %d (refs=%+v)", len(refs), len(want), refs)
	}
	for _, r := range refs {
		if r.Ecosystem != intel.EcosystemCargo {
			t.Errorf("ref %q: ecosystem = %q, want crates.io", r.Name, r.Ecosystem)
		}
		if r.Source != "Cargo.lock" {
			t.Errorf("ref %q: source = %q, want Cargo.lock", r.Name, r.Source)
		}
		v, ok := want[r.Name]
		if !ok {
			t.Errorf("unexpected crate %q (probably a non-registry leak)", r.Name)
			continue
		}
		if r.Version != v {
			t.Errorf("crate %q: version = %q, want %q", r.Name, r.Version, v)
		}
	}
}

func TestParseCargo_ExcludesGitAndPathDeps(t *testing.T) {
	// from-git has source=git+..., my-app has no source. Both
	// must NOT appear in refs even though their [[package]] block
	// is well-formed.
	refs, err := ParseCargo(Target{
		Ecosystem: intel.EcosystemCargo,
		Path:      filepath.Join("testdata", "cargo-compromised", "Cargo.lock"),
		Source:    "Cargo.lock",
	})
	if err != nil {
		t.Fatalf("ParseCargo: %v", err)
	}
	for _, r := range refs {
		if r.Name == "from-git" {
			t.Errorf("git-sourced crate leaked: %+v", r)
		}
		if r.Name == "my-app" {
			t.Errorf("source-less workspace member leaked: %+v", r)
		}
	}
}

func TestParseCargo_MalformedBlockDoesNotPanic(t *testing.T) {
	// Truncated Cargo.lock (open [[package]] block, missing
	// version field). The parser should return whatever it could
	// extract without panicking.
	tmp := t.TempDir()
	path := filepath.Join(tmp, "Cargo.lock")
	writeFile(t, path, "[[package]]\nname = \"trunc\"\n")
	refs, err := ParseCargo(Target{Ecosystem: intel.EcosystemCargo, Path: path, Source: "Cargo.lock"})
	if err != nil {
		t.Fatalf("ParseCargo: %v", err)
	}
	if len(refs) != 0 {
		t.Errorf("expected zero refs from version-less block, got %+v", refs)
	}
}

func TestParseCargo_EmptyLockfileReturnsEmpty(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "Cargo.lock")
	writeFile(t, path, "# Generated by Cargo\n")
	refs, err := ParseCargo(Target{Ecosystem: intel.EcosystemCargo, Path: path, Source: "Cargo.lock"})
	if err != nil {
		t.Fatalf("ParseCargo: %v", err)
	}
	if len(refs) != 0 {
		t.Errorf("empty Cargo.lock should produce zero refs, got %+v", refs)
	}
}
