package packagecheck

import (
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/garagon/aguara/internal/intel"
	"github.com/stretchr/testify/require"
)

// writeYarn writes content to a yarn.lock in a fresh temp dir and
// returns a Target pointing at it.
func writeYarn(t *testing.T, content string) Target {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "yarn.lock")
	require.NoError(t, os.WriteFile(path, []byte(content), 0o600))
	return Target{Ecosystem: intel.EcosystemNPM, Path: path, Source: "yarn.lock"}
}

const yarnHeader = "# THIS IS AN AUTOGENERATED FILE.\n# yarn lockfile v1\n\n\n"

func TestParseYarnLock_BasicAndScoped(t *testing.T) {
	refs, err := ParseYarnLock(writeYarn(t, yarnHeader+`lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#abc"
  integrity sha512-FAKE==

"@scope/pkg@^1.2.0":
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/@scope/pkg/-/pkg-1.2.3.tgz#def"
`))
	require.NoError(t, err)
	require.ElementsMatch(t, []string{"lodash@4.17.21", "@scope/pkg@1.2.3"}, refSet(refs))
	for _, r := range refs {
		require.Equal(t, intel.EcosystemNPM, r.Ecosystem)
		require.Equal(t, "yarn.lock", r.Source)
	}
}

func TestParseYarnLock_CommaSeparatedDescriptors(t *testing.T) {
	// Multiple ranges for the same package share one resolution block
	// and must emit exactly one ref.
	refs, err := ParseYarnLock(writeYarn(t, yarnHeader+`lodash@^4.17.0, lodash@^4.17.11, lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#abc"
`))
	require.NoError(t, err)
	require.Equal(t, []string{"lodash@4.17.21"}, refSet(refs))
}

func TestParseYarnLock_QuotedScopedMultiDescriptor(t *testing.T) {
	refs, err := ParseYarnLock(writeYarn(t, yarnHeader+`"@babel/core@^7.0.0", "@babel/core@^7.1.0":
  version "7.5.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.5.0.tgz#abc"
`))
	require.NoError(t, err)
	require.Equal(t, []string{"@babel/core@7.5.0"}, refSet(refs))
}

func TestParseYarnLock_SkipsNonRegistrySources(t *testing.T) {
	// file: / link: / workspace: / portal: / patch: / git / and the
	// npm: alias protocol are all non-registry and must be skipped;
	// only the clean registry entry survives.
	refs, err := ParseYarnLock(writeYarn(t, yarnHeader+`clean@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/clean/-/clean-1.0.0.tgz#abc"

"local@file:../local-pkg":
  version "2.0.0"

"linked@link:../linked":
  version "3.0.0"

"ws@workspace:packages/ws":
  version "0.0.0"

"aliased@npm:real-pkg@^1.0.0":
  version "1.5.0"
  resolved "https://registry.yarnpkg.com/real-pkg/-/real-pkg-1.5.0.tgz#abc"

"patched@patch:patched@^1.0.0#./p.patch":
  version "1.0.0"

"from-git@git+https://github.com/u/repo.git":
  version "1.0.0"
`))
	require.NoError(t, err)
	require.Equal(t, []string{"clean@1.0.0"}, refSet(refs))
}

func TestParseYarnLock_DedupAndDistinctVersions(t *testing.T) {
	// Same (name, version) across two blocks dedupes; different
	// versions of the same name both survive.
	refs, err := ParseYarnLock(writeYarn(t, yarnHeader+`foo@^1.0.0:
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/foo/-/foo-1.2.3.tgz#a"

foo@~1.2.0:
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/foo/-/foo-1.2.3.tgz#a"

foo@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/foo/-/foo-2.0.0.tgz#b"
`))
	require.NoError(t, err)
	require.ElementsMatch(t, []string{"foo@1.2.3", "foo@2.0.0"}, refSet(refs))
}

func TestParseYarnLock_DependencyNamedVersionNotMiscaptured(t *testing.T) {
	// A nested dependency literally named "version" must NOT be
	// mistaken for the entry's resolved version. yarn writes the
	// entry's version first, so first-match wins.
	refs, err := ParseYarnLock(writeYarn(t, yarnHeader+`pkg@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/pkg/-/pkg-1.0.0.tgz#a"
  dependencies:
    version "^9.9.9"
    lodash "^4.17.0"
`))
	require.NoError(t, err)
	require.Equal(t, []string{"pkg@1.0.0"}, refSet(refs))
}

func TestParseYarnLock_DeterministicOrder(t *testing.T) {
	refs, err := ParseYarnLock(writeYarn(t, yarnHeader+`zeta@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/zeta/-/zeta-1.0.0.tgz#a"

alpha@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/alpha/-/alpha-2.0.0.tgz#b"

"@scope/mid@^1.0.0":
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/@scope/mid/-/mid-1.0.0.tgz#c"
`))
	require.NoError(t, err)
	require.Equal(t, []string{"@scope/mid@1.0.0", "alpha@2.0.0", "zeta@1.0.0"}, refSet(refs))
}

func TestParseYarnLock_BerryDeclined(t *testing.T) {
	// A yarn Berry (v2+) lockfile carries __metadata: and a different
	// grammar. The v1 parser must decline it (return no refs) rather
	// than misread the unquoted `version:` values.
	refs, err := ParseYarnLock(writeYarn(t, `# This file is generated by running "yarn install"
__metadata:
  version: 6
  cacheKey: 8

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: abc
  languageName: node
  linkType: hard
`))
	require.NoError(t, err)
	require.Empty(t, refs, "Berry lockfile must be declined, not misparsed")
}

func TestYarnDescriptorParse(t *testing.T) {
	cases := []struct {
		desc, name, rng string
		ok              bool
	}{
		{"lodash@^4.17.0", "lodash", "^4.17.0", true},
		{`"@scope/pkg@^1.2.0"`, "@scope/pkg", "^1.2.0", true},
		{"alias@npm:real@^1.0.0", "alias", "npm:real@^1.0.0", true},
		{"@scope/pkg@npm:other@^1.0.0", "@scope/pkg", "npm:other@^1.0.0", true},
		{"noatsign", "", "", false},
		{"", "", "", false},
	}
	for _, c := range cases {
		n, r, ok := yarnDescriptorParse(c.desc)
		require.Equalf(t, c.ok, ok, "ok for %q", c.desc)
		if c.ok {
			require.Equalf(t, c.name, n, "name for %q", c.desc)
			require.Equalf(t, c.rng, r, "range for %q", c.desc)
		}
	}
}

func TestIsExactYarnVersion(t *testing.T) {
	require.True(t, isExactYarnVersion("4.17.21"))
	require.True(t, isExactYarnVersion("1.0.0-beta.1+build"))
	require.False(t, isExactYarnVersion(""))
	require.False(t, isExactYarnVersion("^1.0.0"))
	require.False(t, isExactYarnVersion(">=1.0.0 <2.0.0"))
	require.False(t, isExactYarnVersion("npm:real@1.0.0"))
}

func TestRunner_YarnLockHit(t *testing.T) {
	snap := intel.Snapshot{
		SchemaVersion: intel.CurrentSchemaVersion,
		GeneratedAt:   time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC),
		Records: []intel.Record{{
			ID:        "MAL-YARN",
			Ecosystem: intel.EcosystemNPM,
			Name:      "evil-pkg",
			Kind:      intel.KindMalicious,
			Versions:  []string{"1.2.3"},
		}},
	}
	runner := &Runner{Matcher: intel.NewMatcher(snap)}
	target := writeYarn(t, yarnHeader+`evil-pkg@^1.0.0:
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/evil-pkg/-/evil-pkg-1.2.3.tgz#a"

safe@^9.0.0:
  version "9.9.9"
  resolved "https://registry.yarnpkg.com/safe/-/safe-9.9.9.tgz#b"
`)
	res, err := runner.Run([]Target{target})
	require.NoError(t, err)
	require.Len(t, res.Ecosystems, 1)
	require.Equal(t, "yarn.lock", res.Ecosystems[0].Source)
	require.Equal(t, 2, res.Ecosystems[0].PackagesRead)
	require.Equal(t, 1, res.Ecosystems[0].FindingsCount)
	require.Len(t, res.Hits, 1)
	require.Equal(t, "evil-pkg", res.Hits[0].Ref.Name)
	require.Equal(t, "MAL-YARN", res.Hits[0].Record.ID)
}

func TestDiscover_PicksYarnLock(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "yarn.lock"), []byte("# yarn lockfile v1\n"), 0o600))
	targets, err := Discover(dir, []string{intel.EcosystemNPM})
	require.NoError(t, err)
	require.Len(t, targets, 1)
	require.Equal(t, "yarn.lock", targets[0].Source)
	require.Equal(t, intel.EcosystemNPM, targets[0].Ecosystem)
}
