// Code generated by tools/update-intel; DO NOT EDIT.
// To regenerate (download dumps manually, then):
//
//   go run ./tools/update-intel \
//       --from-zip ./osv-npm.zip --ecosystem npm \
//       --from-zip ./osv-pypi.zip --ecosystem PyPI \
//       --out internal/incident/generated_intel.go

package incident

import (
	"time"

	"github.com/garagon/aguara/internal/intel"
)

// EmbeddedIntelSnapshot is the OSV-derived snapshot baked into the binary.
// Combined with KnownCompromisedSnapshot() through the matcher's
// merge semantics so manual emergency entries keep display priority
// over OSV refreshes for the same advisory ID.
//
// This file ships empty until the maintainer regenerates it from a
// fresh OSV all.zip dump pre-release. Sources stays empty too so
// the IntelSummary does not advertise an OSV provenance the binary
// has not actually used; the importer fills both lists in lockstep
// on every regeneration.
var EmbeddedIntelSnapshot = intel.Snapshot{
	SchemaVersion: 1,
	GeneratedAt:   time.Date(2026, time.May, 15, 0, 0, 0, 0, time.UTC),
	Sources:       []intel.SourceMeta{},
	Records:       []intel.Record{},
}
